# -*- coding: utf-8 -*-
"""train_Plant_watering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0hC5d09PR5tIn8sGLRWXpkchLT04-_3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.metrics import BinaryAccuracy
import joblib
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv("plant_watering_training_dataset.csv")
df.head()

df.info()

df.columns

df.isnull().sum()

x = df.drop("Water_Needed", axis=1)
y = df["Water_Needed"]

# Split Dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

# Feature Scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Save scaler
joblib.dump(scaler, "plant_scaler.pkl")

# Build ANN Model
# ANN Model
model = Sequential([
    Input(shape=(5,)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Early Stopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# Train Model
history = model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

# Evaluate
loss, accuracy = model.evaluate(x_test, y_test)

print(f"\nTest Accuracy: {accuracy*100:.2f}%")

# Save Model
model.save("plant_watering_ann.keras")

print("\nModel and Scaler Saved Successfully!")

